# Generated by Django 4.1.3 on 2022-12-03 21:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ingredients', tinymce.models.HTMLField()),
                ('instructions', tinymce.models.HTMLField()),
                ('spiel', tinymce.models.HTMLField(blank=True)),
                ('time_in_mins', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('related_recipes', models.ManyToManyField(blank=True, to='recipes.recipe')),
                ('tags', models.ManyToManyField(blank=True, to='recipes.tag')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
