# Generated by Django 2.0.7 on 2018-07-14 06:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='spiel',
            field=tinymce.models.HTMLField(default='', verbose_name='Spiel'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=tinymce.models.HTMLField(verbose_name='Instructions'),
        ),
    ]
