# Generated by Django 2.0.7 on 2018-07-14 06:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180714_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='spiel',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Spiel'),
        ),
    ]
