# Generated by Django 2.0.7 on 2018-07-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180714_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recipes.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_in_mins',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
